// Generated by CoffeeScript 1.4.0
(function() {
  var test, tests, _i, _len;

  tests = ["base-redis-test", "redis-getter-test", "redis-setter-test", "channel-manager-test", "redis-mq-test"];

  for (_i = 0, _len = tests.length; _i < _len; _i++) {
    test = tests[_i];
    require("./" + test);
  }

}).call(this);
