// Generated by CoffeeScript 1.4.0
(function() {
  var ChannelManager, RedisMQ;

  RedisMQ = require('./lib/redis-mq/RedisMQ').RedisMQ;

  ChannelManager = require('./lib/redis-mq/ChannelManager').ChannelManager;

  exports.RedisMQ = RedisMQ;

  exports.ChannelManager = ChannelManager;

}).call(this);
