// Generated by CoffeeScript 1.4.0
(function() {
  var ChannelManager, RedisQueue;

  RedisQueue = require('./lib/redis-mq/RedisMQ').RedisQueue;

  ChannelManager = require('./lib/redis-mq/ChannelManager').ChannelManager;

  exports.RedisQueue = RedisQueue;

  exports.ChannelManager = ChannelManager;

}).call(this);
