// Generated by CoffeeScript 1.4.0
(function() {
  var RedisBase, RedisHelper, _;

  _ = require("underscore");

  RedisHelper = (function() {

    function RedisHelper() {}

    RedisHelper.buildKey = function(delimiter, parts) {
      return parts.join(delimiter);
    };

    return RedisHelper;

  })();

  RedisBase = (function() {

    function RedisBase(options) {
      var defaults, key, value;
      defaults = {
        delimiter: "|",
        client: null,
        id: null,
        redis_base: null
      };
      options = _.extend({}, defaults, options);
      for (key in options) {
        value = options[key];
        if (value) {
          this[key] = value;
        } else {
          throw "No value found for required key " + key + " in RedisBase.";
        }
      }
      this.keys_waiting = 0;
    }

    RedisBase.prototype.onDone = function(callback) {
      return this.listener = callback;
    };

    RedisBase.prototype.buildKey = function(key) {
      return RedisHelper.buildKey(this.delimiter, [this.redis_base, this.id, key]);
    };

    RedisBase.prototype.isDone = function() {
      return this.keys_waiting === 0;
    };

    return RedisBase;

  })();

  exports.RedisBase = RedisBase;

  exports.RedisHelper = RedisHelper;

}).call(this);
